//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turagentstvo.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dates
    {
        public int id { get; set; }
        public System.DateTime dates { get; set; }
    }
}
