//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turagentstvo.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourAgencyMDEntities2 : DbContext
    {
        private static TourAgencyMDEntities2 _context;

        public static TourAgencyMDEntities2 GetContext()
        {
            if (_context == null)
                _context = new TourAgencyMDEntities2();

            return _context;
        }

        public TourAgencyMDEntities2()
            : base("name=TourAgencyMDEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Countrys> Countrys { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<TourHotels> TourHotels { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<TourTypes> TourTypes { get; set; }
        public virtual DbSet<Dates> Dates { get; set; }

        public static User currentuser = null;
    }
}
