//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turagentstvo.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        public int TourID { get; set; }
        public string ImageTour { get; set; }
        public string TourName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> TicketsCount { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> isActual { get; set; }
        public string TourType { get; set; }
        public string Actual { get; set; }
    }
}
